name: openalea-meta
channels:
  - conda-forge
  - openalea3
  - openalea3/label/rc
  - openalea3/label/dev
dependencies:
  - python
  - openalea.plantgl
  - openalea.lpy
  - openalea.core
  - openalea.widgets
  - openalea.mtg 
  - openalea.scipack
  - openalea.oalab
  - openalea.grapheditor
  - openalea.visualea
  - openalea.weberpenn
  - openalea.rsml 
  - openalea.ratp
  - openalea.caribu
  - openalea.astk
  - openalea.adel
  - openalea.spice
  - openalea.hydroroot
  - openalea.phenomenal
  - openalea.hydroshoot
  - openalea.wheatfspm
