name: openalea-meta
channels:
  - conda-forge
  - openalea3
  - openalea3/label/rc
  - openalea3/label/dev
dependencies:
  - python
  - openalea.plantgl=3.22.3
  - openalea.lpy=3.15.4
  - openalea.core=2.5.0
  - openalea.widgets=1.1.2
  - openalea.mtg=2.3.0
  - openalea.scipack=2.5.2
  - openalea.oalab=2.5.0
  - openalea.grapheditor=2.5.0
  - openalea.visualea=2.5.0
  - openalea.weberpenn=2.5.0
  - openalea.rsml=1.5.0
  - openalea.ratp=2.1.1.dev
  - openalea.caribu=8.2.1
  - openalea.astk=3.1.0
  - openalea.adel=2.1.0
  - openalea.spice=1.1.0
  - openalea.hydroroot=2.1.0
  - openalea.phenomenal=1.10.2
  - openalea.hydroshoot=5.3.0
  - openalea.wheatfspm=2.0.1.dev
